consul:
    image: qnib/consul
    ports:
     - "8500:8500"
    environment:
    - DC_NAME=dc1
    dns: 127.0.0.1
    hostname: consul
    privileged: true

openhab:
    image: qnib/openhab
    ports:
    - "8080:8080"
    links:
    - consul:consul
    environment:
    - DC_NAME=dc1
    dns: 127.0.0.1
    hostname: openhab
    privileged: true
